import { IAgreementData } from '../../types';

export const agreementsData: IAgreementData[] = [
  {
    title: 'Согласие на обработку персональных данных:',
    text: 'Настоящим в соответствии с Федеральным законом № 152-ФЗ «О персональных данных» от 27.07.2006 года Вы подтверждаете свое согласие на обработку компанией ООО "ТИНДЕР-АВТО" персональных данных: сбор, систематизацию, накопление, хранение, уточнение (обновление, изменение), использование, передачу исключительно в целях продажи программного обеспечения на Ваше имя, как это описано ниже, блокирование, обезличивание, уничтожение Компания ООО "ТИНДЕР-АВТО" гарантирует конфиденциальность получаемой информации. Обработка персональных данных осуществляется в целях эффективного договоров и иных обязательств, принятых компанией ООО ТИНДЕР-АВТО в качестве обязательных к исполнению В случае необходимости предоставления Ваших персональных данных правообладателю, дистрибьютору или реселлеру программного обеспечения в целях регистрации программного обеспечения на ваше имя, вы даёте согласие на передачу ваших персональных данных. Компания ООО "ТИНДЕР-АВТО" гарантирует, что правообладатель, дистрибьютор или реселлер программного обеспечения осуществляет защиту персональных данных на условиях, аналогичных изложенным в Политике конфиденциальности персональных данных. Настоящее согласие распространяется на следующие Ваши персональные данные: фамилия, имя и отчество, адрес электронной почты, данные автомобиля, контактный телефон, платёжные реквизиты. Срок действия согласия является неограниченным. Вы можете в любой момент отозвать настоящее согласие, направив письменное уведомления на электронный адрес: boss@auto-ginder.gq с пометкой «Отзыв согласия на обработку персональных данных». Гарантирую, что представленная мной информация является полной, точной и достоверной, а также что при представлении информации не нарушаются действующее законодательство Российской Федерации, законные права и интересы третьих лиц. Вся представленная информация заполнена мною в отношении себя лично. Настоящее согласие действует в течение всего периода хранения персональных данных, если иное не предусмотрено законодательством Российской Федерации.',
  },
  {
    title: 'Политика конфиденциальности:',
    text: 'Длинный текст с политикой конфиденциальности. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur enim eos laborum molestias, nemo numquam quas qui totam? Ab ad animi autem consequuntur cum deleniti deserunt dicta dolore ducimus eaque eius est et eum exercitationem explicabo facere fugit in incidunt ipsa laboriosam libero magni necessitatibus nihil, pariatur perspiciatis porro possimus quam quasi quis quo rem repudiandae sint, sit ullam vel voluptatem voluptatibus. Aut consectetur distinctio doloribus eius exercitationem fugit ipsa libero maxime molestiae non officiis omnis, perferendis porro qui quia ut vitae voluptatibus. Aliquid amet atque, autem explicabo harum id impedit maiores nam, nemo numquam officia quae rem, sapiente suscipit..',
  },
  {
    title: 'Пользовательское соглашение:',
    text: ' Длинный текст с пользовательским соглашениме. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur enim eos laborum molestias, nemo numquam quas qui totam? Ab ad animi autem consequuntur cum deleniti deserunt dicta dolore ducimus eaque eius est et eum exercitationem explicabo facere fugit in incidunt ipsa laboriosam libero magni necessitatibus nihil, pariatur perspiciatis porro possimus quam quasi quis quo rem repudiandae sint, sit ullam vel voluptatem voluptatibus. Aut consectetur distinctio doloribus eius exercitationem fugit ipsa libero maxime molestiae non officiis omnis, perferendis porro qui quia ut vitae voluptatibus. Aliquid amet atque, autem explicabo harum id impedit maiores nam, nemo numquam officia quae rem, sapiente suscipit..',
  },
];
